name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Creer fichier .env
        run: |
              echo "MYSQL_HOST=mysql" >> .env
              echo "MONGODB_HOST=mongo" >> .env
              echo "MONGODB_PORT=27017" >> .env
              echo "MYSQL_DB_NAME=labo01_db" >> .env
              echo "MONGODB_NAME=labo01_db" >> .env
              echo "DB_USERNAME=labo01" >> .env
              echo "DB_PASSWORD=labo01" >> .env
              echo "MONGO_INITDB_ROOT_USERNAME=labo01" >> .env
              echo "MONGO_INITDB_ROOT_PASSWORD=labo01" >> .env


      - name: Restart app
        run: |
          docker-compose down || true
          docker-compose up -d --build